Repository Green-Whale-Studios/The-Vega-Initiative, pull requests merged in 2025-03, with the labels that each got.

#10 Pygbag compatibility patch
  game.py
Labels: bug, enhancement, help wanted

#14 Pygbag GitHub pages
  .github/workflows/pygbag.yml
  .gitignore
  localhost.md
  main.py
Labels: bug, enhancement, part fixed

#20 Rewrote code to use logging as a logger
  main.py
Labels: bug, enhancement

#22 Push updated log code to main
  main.py
Labels: enhancement

#45 Update README.md
  README.md
Labels: documentation, enhancement

#44 Delete localhost.md
  localhost.md
Labels: documentation, enhancement

#48 Add copyright declaration
  LICENSE
Labels: documentation, enhancement

#50 Make repo match community guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  SECURITY.md
Labels: documentation, enhancement

#31 Make zoom multiplier function
  main.py
Labels: enhancement, help wanted, part fixed

#55 Push all of the dev commits to main
  main.py
  requirements.txt
Labels: bug, documentation, enhancement, help wanted, good first issue, major bug

#53 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#58 Push latest build to main
  .github/workflows/pygbag.yml
  main.py
  pathfinding.py
Labels: bug, enhancement
